---
title: "Milestone 5"
author: "Sydney Sorkin"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
## Purpose
  
This project seeks to do a comprehensive review of Harvard University's efforts to publicize its men's and women's varsity sports teams via various official Harvard affiliated Twitter accounts in the 2018-2019 academic year. The research is centered around the questions: Does Harvard provide equal media coverage its men's and women's sports teams? If not, which teams are favored? Are those teams favored due to a gender bias or greater team success than others? 
  
## The Data  
  
The data was gathered through the R package "Rtweets", accessed through a Twitter Developer account and relevant API's. 

## About Me
  
My name is Sydney Sorkin and I am a Harvard undergrad studying Government and Psychology. I play on the Varsity Women's hockey team. I am passionate about political and media communication, especially as it relates to sports.   
Contact me at ssorkin@college.harvard.edu

## Source Code
  
The source code used to create this project can be found here. 

